ARG PYTHON_VERSION=slim 

FROM python:${PYTHON_VERSION}

WORKDIR /workspace

# this is used for build test. 
# liblzma-dev libbz2-dev libdeflate-dev are required for full feature htslib library
RUN apt-get update && apt-get install --no-install-recommends -y autoconf automake gcc \
    libcurl4-openssl-dev make git libc6-dev zlib1g-dev libssl-dev && \
    rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install -r requirements.txt && pip install pytest pytest-cov

# build cyvcf2
RUN CYVCF2_HTSLIB_CONFIGURE_OPTIONS="--enable-s3 --disable-lzma --disable-bz2" \
    CYTHONIZE=1 python setup.py build_ext -i
