ARG PYTHON_VERSION=alpine 

FROM python:${PYTHON_VERSION}

WORKDIR /workspace

RUN apk add --no-cache build-base autoconf automake cmake ninja git xz-dev curl-dev libdeflate-dev bzip2-dev

RUN pip install pytest pytest-cov

COPY . .

# build cyvcf2
RUN CYVCF2_HTSLIB_CONFIGURE_OPTIONS="--enable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate" \
    python -m pip install -v -e .
