#!/bin/bash

set -euo pipefail

# same with python
export MACOSX_DEPLOYMENT_TARGET=10.9

brew install automake libdeflate
brew unlink xz

# build liblzma and libdelfate for deployment target 10.9

XZ_VERSION=5.4.6
curl -L -o xz-$XZ_VERSION.tar.gz "https://github.com/tukaani-project/xz/releases/download/v$XZ_VERSION/xz-$XZ_VERSION.tar.gz"
tar -xf xz-$XZ_VERSION.tar.gz
cd xz-$XZ_VERSION
cmake -B build && cmake --build build
cd ./build && sudo make install

LIBDEFLATE_VERSION=1.20
curl -L -o libdeflate-v"$LIBDEFLATE_VERSION".tar.gz https://github.com/ebiggers/libdeflate/archive/refs/tags/v"$LIBDEFLATE_VERSION".tar.gz
tar xzf libdeflate-v"$LIBDEFLATE_VERSION".tar.gz
cd libdeflate-"$LIBDEFLATE_VERSION"
cmake -B build && cmake --build build
cd ./build && sudo make install
