#!/bin/bash

set -euo pipefail

export DYLD_LIBRARY_PATH=/usr/local/lib
# same with python
export MACOSX_DEPLOYMENT_TARGET=10.9

brew install automake
brew unlink xz

# build liblzma and libdelfate for muti arch

XZ_VERSION=5.4.5
curl -L -o xz-$XZ_VERSION.tar.gz "https://github.com/tukaani-project/xz/releases/download/v$XZ_VERSION/xz-$XZ_VERSION.tar.gz"
tar -xf xz-$XZ_VERSION.tar.gz
cd xz-$XZ_VERSION
cmake -B build && cmake --build build
cd ./build && make install

LIBDEFLATE_VERSION=1.19
curl -L -o libdeflate-v"$LIBDEFLATE_VERSION".tar.gz https://github.com/ebiggers/libdeflate/archive/refs/tags/v"$LIBDEFLATE_VERSION".tar.gz
tar xzf libdeflate-v"$LIBDEFLATE_VERSION".tar.gz
cd libdeflate-"$LIBDEFLATE_VERSION"
cmake -B build && cmake --build build
cd ./build && make install
